"""empty message

Revision ID: 10477f9c3c01
Revises: 
Create Date: 2020-03-05 20:54:04.903234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10477f9c3c01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('spotify_users',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('uri', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spotify_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('expires_dt', sa.DateTime(), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=6), nullable=False),
    sa.Column('spotify_id', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['spotify_id'], ['spotify_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spotify_tokens')
    op.drop_table('spotify_users')
    op.drop_table('users')
    # ### end Alembic commands ###
