"""Add foreign keys

Revision ID: 39b678cf31d3
Revises: 7bd4f005d04e
Create Date: 2020-02-21 01:31:50.869652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b678cf31d3'
down_revision = '7bd4f005d04e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spotify_tokens', sa.Column('spotify_id', sa.String(length=80), nullable=False))
    op.create_foreign_key(None, 'spotify_tokens', 'spotify_users', ['spotify_id'], ['id'])
    op.add_column('spotify_users', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'spotify_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spotify_users', type_='foreignkey')
    op.drop_column('spotify_users', 'user_id')
    op.drop_constraint(None, 'spotify_tokens', type_='foreignkey')
    op.drop_column('spotify_tokens', 'spotify_id')
    # ### end Alembic commands ###
