"""Change user foreign key to not required

Revision ID: 6756ad38cdd6
Revises: 39b678cf31d3
Create Date: 2020-02-22 00:18:07.570932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6756ad38cdd6'
down_revision = '39b678cf31d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spotify_tokens', 'spotify_id',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('spotify_users', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spotify_users', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('spotify_tokens', 'spotify_id',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###
